# Generated by Django 4.2 on 2026-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(blank=True, help_text='Optional: Set a specific date for this reminder', null=True),
        ),
    ]
