# Generated by Django 4.2 on 2026-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Antibiotic, Painkiller', max_length=100, null=True),
        ),
    ]
