# Generated by Django 4.2 on 2026-04-28 14:05

from django.db import migrations
from django.contrib.auth.models import User


def create_sample_medicines(apps, schema_editor):
    """Create sample medicines data for demonstration"""
    Medicine = apps.get_model('medicines', 'Medicine')
    
    # Sample medicines data
    sample_medicines = [
        {'name': 'Paracetamol', 'dosage': '500mg', 'quantity': 50},
        {'name': 'Ibuprofen', 'dosage': '400mg', 'quantity': 30},
        {'name': 'Aspirin', 'dosage': '300mg', 'quantity': 45},
        {'name': 'Amoxicillin', 'dosage': '250mg', 'quantity': 20},
        {'name': 'Cetirizine', 'dosage': '10mg', 'quantity': 60},
        {'name': 'Vitamin D3', 'dosage': '1000 IU', 'quantity': 90},
        {'name': 'Vitamin C', 'dosage': '500mg', 'quantity': 100},
        {'name': 'Omega-3', 'dosage': '1000mg', 'quantity': 60},
        {'name': 'Lisinopril', 'dosage': '10mg', 'quantity': 30},
        {'name': 'Metformin', 'dosage': '500mg', 'quantity': 60},
        {'name': 'Atorvastatin', 'dosage': '20mg', 'quantity': 30},
        {'name': 'Omeprazole', 'dosage': '20mg', 'quantity': 14},
        {'name': 'Loratadine', 'dosage': '10mg', 'quantity': 30},
        {'name': 'Azithromycin', 'dosage': '500mg', 'quantity': 6},
        {'name': 'Naproxen', 'dosage': '250mg', 'quantity': 20},
    ]
    
    # Get or create a demo user
    User = apps.get_model('auth', 'User')
    demo_user, created = User.objects.get_or_create(
        username='demo',
        defaults={
            'email': 'demo@example.com',
            'first_name': 'Demo',
            'last_name': 'User',
            'is_active': True,
        }
    )
    
    # Create sample medicines for the demo user
    for med_data in sample_medicines:
        Medicine.objects.get_or_create(
            user=demo_user,
            name=med_data['name'],
            defaults={
                'dosage': med_data['dosage'],
                'quantity': med_data['quantity']
            }
        )


def reverse_sample_medicines(apps, schema_editor):
    """Remove sample medicines data"""
    Medicine = apps.get_model('medicines', 'Medicine')
    User = apps.get_model('auth', 'User')
    
    # Remove demo user and their medicines
    try:
        demo_user = User.objects.get(username='demo')
        Medicine.objects.filter(user=demo_user).delete()
        demo_user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_category'),
    ]

    operations = [
        migrations.RunPython(create_sample_medicines, reverse_sample_medicines),
    ]
